
window:
  padding:
    x: 10
    y: 5

  decorations: full

  opacity: 1.0
  dynamic_title: true

  history: 10000
  multiplier: 3

font:
  normal:
    family: Maple Mono SC NF
    #style: Regular

  bold:
    family: Maple Mono SC NF
    #style: Bold

  
  italic:
    family: Maple Mono SC NF
    #style: Italic

  bold_italic:
    family: Maple Mono SC NF
    #style: Bold Italic

  size: 12

# Colors (Tokyo Night) Emilia Rice
colors:
  primary:
    background: '#1a1b26'
    foreground: '#c0caf5'

  normal:
    black:   '#414868'
    red:     '#f7768e'
    green:   '#9ece6a'
    yellow:  '#e0af68'
    blue:    '#7aa2f7'
    magenta: '#bb9af7'
    cyan:    '#7dcfff'
    white:   '#787c99'

  bright:
    black:   '#414868'
    red:     '#f7768e'
    green:   '#9ece6a'
    yellow:  '#e0af68'
    blue:    '#7aa2f7'
    magenta: '#bb9af7'
    cyan:    '#7dcfff'
    white:   '#c0caf5'

selection:
  save_to_clipboard: false

cursor:
  style:
    shape: Block
    blinking: On
    
  unfocused_hollow: false 
  blink_interval: 550

live_config_reload: true
