#!/usr/bin/env bash

########### Def vars

#export RICETHEME=$(<$HOME/.config/bspwm/rice.cfg)
PATH="$HOME/.config/bspwm/scripts:$PATH"
bspdir="$HOME/.config/bspwm"
polydir="$HOME/.config/bspwm/theme/polybar"
export defnetif=$(ip route | grep '^default' | awk '{print $5}' | head -n1)

## You can edit this.
BSPWM_BORDER='0'
BSPWM_GAP='10'

########### Functions

function launch() {
  local running
  running="$(pgrep -x "$1")"
  [ "$running" ] && kill -9 $(pgrep -x $1) 2> /dev/null
  eval "$* &"
}

function killeww() {
  if [[ `pidof eww` ]]; then 
		pkill eww
  fi
}

function ReloadTerms() {
  cat $HOME/.config/bspwm/theme/alacrittyrc > $HOME/.config/alacritty/alacritty.yml
}

function SetBspwmConf() {
	bspc config border_width "$BSPWM_BORDER"
	bspc config top_padding "$2"
	bspc config bottom_padding "$3"
	bspc config normal_border_color "$4" 
	bspc config active_border_color "$5"
	bspc config focused_border_color "$6"
	bspc config presel_feedback_color "$7"
	bspc config left_padding "$8"
	bspc config right_padding "$9"
	bspc config window_gap "$BSPWM_GAP"
}

########### Workspaces

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5' '6'
		#bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' ''
		let name++
	done
}

workspaces

########### Launch The Rice!!
		
SetBspwmConf "$BSPWM_BORDER" 60 5 "#C574DD" "#C574DD" "#8897F4" "#FF4971" 5 5 "$BSPWM_GAP"
		  
killeww
launch polybar -q pam1 -c ${polydir}/config.ini
polybar -q pam2 -c ${polydir}/config.ini &
polybar -q pam3 -c ${polydir}/config.ini &
polybar -q pam4 -c ${polydir}/config.ini &
polybar -q pam5 -c ${polydir}/config.ini &
polybar -q pam6 -c ${polydir}/config.ini &
launch dunst -config ${bspdir}/dunstrc-dark
		  

########### bspwm conf

bspc config external_rules_command ~/.config/bspwm/scripts/ExternalRules

bspc config single_monocle                true
bspc config split_ratio                   0.5
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config focus_follows_pointer         true
bspc config center_pseudo_tiled			  true

bspc config pointer_modifier              mod4 
bspc config pointer_action1               move 
bspc config pointer_action2               resize_side 
bspc config pointer_action3               resize_corner

bspc config automatic_scheme              longest_side
bspc config initial_polarity              second_child

bspc config remove_disabled_monitors      true 
bspc config merge_overlapping_monitors    true

bspc config pointer_motion_interval       16

########## AutoStart Apps

#ReloadTerms
launch sxhkd -c ${bspdir}/sxhkdrc
launch picom --config ${bspdir}/theme/picom.conf
#launch picom --legacy-backends --config ${bspdir}/rices/$RICETHEME/picom.conf
	
if [[ ! `pidof polkit-gnome-authentication-agent-1` ]]; then
	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

xsetroot -cursor_name left_ptr
exec --no-startup-id libinput-gestures-setup start
export _JAVA_AWT_WM_NONREPARENTING=1
wmname LG3D