#!/usr/bin/env bash

#weather=$(curl -s wttr.in/London?format=3)
weather=$(curl -s https://wttr.in/?format=3)

if [ $(echo "$weather" | grep -E "(Unknown|curl|HTML)" | wc -l) -gt 0 ]; then
    echo "WEATHER UNAVAILABLE"
else
    #echo "$weather" | awk '{print $1 " "$2" "$3}'
    echo "$weather" | awk '{print}'
fi

